services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  friday:
    build:
      context: .
      dockerfile: Dockerfile
    image: friday:latest
    container_name: friday
    volumes:
      - friday:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${FRIDAY_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
      - 'OPENAI_API_BASE_URL=${OPENAI_API_BASE_URL}'
      - 'OPENAI_API_KEY=${OPENAI_API_KEY}'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  friday: {}
